version: '2'

services:

    smr:
        image: smrealms/smr:latest
        restart: always
        volumes:
            - ./config:/smr/config:ro
            - ./player-upload:/smr/htdocs/upload:rw
        depends_on:
            - smtp
            - mysql
            - nginx

    smtp:
        image: hemberger/postfix-relay
        restart: always
        environment:
            - POSTFIX_myhostname=oberon.fem.tu-ilmenau.de
            - OPENDKIM_DOMAINS=smrealms.de
            - OPENDKIM_SELECTOR=key1
        volumes:
            - ./opendkim:/etc/opendkim/keys/smrealms.de

    mysql:
        image: mysql:5.7
        restart: always
        container_name: ${MYSQL_HOST}
        # By using the default image, we must expose the secrets in
        # the runtime environment (because we can't specify build args).
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER:          smr
            MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
            MYSQL_DATABASE:      smr_live
        volumes:
            - ./data/db:/var/lib/mysql
        # The mysql:5.7+ docker default sql mode uses STRICT_TRANS_TABLES,
        # which is incompatible with the way the SMR database is used.
        # Therefore, we override CMD to omit this sql mode.
        command: ["mysqld", "--sql-mode=NO_ENGINE_SUBSTITUTION"]

    flyway:
        image: smrealms/smr:flyway
        command: -url=jdbc:mysql://${MYSQL_HOST}/smr_live -user=smr -password=${MYSQL_PASSWORD} migrate
        depends_on:
            - mysql

    discord:
        image: smrealms/smr:discordbot
        restart: always
        volumes:
            - ./config:/smr/config:ro
        depends_on:
            - mysql

    irc:
        image: smrealms/smr:ircbot
        restart: always
        volumes:
            - ./config:/smr/config:ro
        depends_on:
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_ABSOLUTE_URI: https://www.smrealms.de:8082
        depends_on:
            - mysql
            - nginx

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
            - "8082:8082"
        volumes:
            - ./nginx:/etc/nginx/conf.d:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - certbot-renewal:/www-certbot

    certbot:
        image: certbot/certbot
        command: "certonly --webroot -d smrealms.de -d www.smrealms.de --webroot-path /www-certbot -m support@smrealms.de --agree-tos"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/log/letsencrypt:/var/log/letsencrypt
            - certbot-renewal:/www-certbot

    # Only used during the initial install of the certificates
    nginx-certbot-install:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/certbot-install:/etc/nginx/conf.d:ro
            - certbot-renewal:/www-certbot

    backup-s3:
        image: hemberger/docker-backup-to-s3
        environment:
            ACCESS_KEY: ${S3_ACCESS_KEY}
            SECRET_KEY: ${S3_SECRET_KEY}
            S3_PATH: s3://smrealms-backup
        volumes:
            - ./backup/daily:/data/daily:ro
            - ./player-upload:/data/player-upload:ro

volumes:
    # Webroot for certificate renewal (temporary storage)
    certbot-renewal:
