version: '2'

services:

    smr:
        image: smrealms/smr:latest
        restart: always
        volumes:
            - ${SMR_CONFIG_DIR}:/smr/config:ro
            - ${SMR_UPLOAD_DIR}:/smr/htdocs/upload:rw
            - /var/run/mysqld:/var/run/mysqld
        depends_on:
            - smtp

    smtp:
        image: hemberger/postfix-relay
        restart: always
        environment:
            - OPENDKIM_DOMAINS=smrealms.de
            - OPENDKIM_SELECTOR=key1
        volumes:
            - ./opendkim:/etc/opendkim/keys/smrealms.de

    discord:
        image: smrealms/smr:discordbot
        restart: always
        volumes:
            - ${SMR_CONFIG_DIR}:/smr/config:ro
            - /var/run/mysqld:/var/run/mysqld

    irc:
        image: smrealms/smr:ircbot
        restart: always
        volumes:
            - ${SMR_CONFIG_DIR}:/smr/config:ro
            - /var/run/mysqld:/var/run/mysqld

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        volumes:
            - ./phpmyadmin/config.php:/etc/phpmyadmin/config.user.inc.php:ro
            - /var/run/mysqld:/var/run/mysqld
